"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-25 10:15:25.662125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('calibration_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('candidate_version', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fundamentals_quarterly',
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('filed_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'period_end', 'filed_date', 'source')
    )
    op.create_table('issues',
    sa.Column('issue_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('issue_id')
    )
    op.create_table('llm_cache',
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('fingerprint')
    )
    op.create_table('llm_calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('tier', sa.String(length=8), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('error', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_calls_created_at'), ['created_at'], unique=False)

    op.create_table('model_versions',
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('parent_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('shadow_started', sa.Date(), nullable=True),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('portfolio_holdings',
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('cost_basis', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('price_bars',
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'day', 'source')
    )
    op.create_table('provider_health',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_health', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_health_name'), ['name'], unique=False)

    op.create_table('scan_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('stages', sa.JSON(), nullable=False),
    sa.Column('excluded_count', sa.Integer(), nullable=False),
    sa.Column('regimes', sa.JSON(), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('scoring_model_version', sa.String(length=64), nullable=False),
    sa.Column('config_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_runs_as_of'), ['as_of'], unique=False)

    op.create_table('securities',
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('company_name', sa.String(length=256), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=False),
    sa.Column('industry', sa.String(length=128), nullable=False),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('is_etf', sa.Boolean(), nullable=False),
    sa.Column('is_adr', sa.Boolean(), nullable=False),
    sa.Column('country_of_incorporation', sa.String(length=8), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('listed_at', sa.Date(), nullable=True),
    sa.Column('delisted_at', sa.Date(), nullable=True),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('watchlist',
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_run_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('session', sa.String(length=16), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_source', sa.String(length=64), nullable=True),
    sa.Column('price_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price_quality', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('deterministic_action', sa.String(length=24), nullable=False),
    sa.Column('final_action', sa.String(length=24), nullable=False),
    sa.Column('size_class', sa.String(length=8), nullable=True),
    sa.Column('sector', sa.String(length=64), nullable=False),
    sa.Column('sector_model', sa.String(length=32), nullable=False),
    sa.Column('regime', sa.String(length=64), nullable=False),
    sa.Column('data_quality', sa.String(length=16), nullable=False),
    sa.Column('committee_status', sa.String(length=24), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('model_config_snapshot', sa.JSON(), nullable=False),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('scoring_model_version', sa.String(length=64), nullable=False),
    sa.Column('decision_model_version', sa.String(length=64), nullable=False),
    sa.Column('agent_prompt_version', sa.String(length=64), nullable=False),
    sa.Column('provider_version', sa.String(length=128), nullable=False),
    sa.Column('config_version', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index('ix_rec_ticker_asof', ['ticker', 'as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_scan_run_id'), ['scan_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_ticker'), ['ticker'], unique=False)

    op.create_table('committee_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('consensus', sa.Float(), nullable=True),
    sa.Column('divergence', sa.String(length=16), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('committee_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_committee_reports_recommendation_id'), ['recommendation_id'], unique=False)

    op.create_table('factor_snapshots',
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('rec_day', sa.Date(), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=False),
    sa.Column('regime', sa.String(length=64), nullable=False),
    sa.Column('scoring_model_version', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    with op.batch_alter_table('factor_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_factor_snapshots_rec_day'), ['rec_day'], unique=False)
        batch_op.create_index(batch_op.f('ix_factor_snapshots_ticker'), ['ticker'], unique=False)

    op.create_table('paper_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('recommended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('entry_day', sa.Date(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('regime', sa.String(length=64), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=False),
    sa.Column('stop', sa.Float(), nullable=False),
    sa.Column('target1', sa.Float(), nullable=False),
    sa.Column('target2', sa.Float(), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('exits', sa.JSON(), nullable=False),
    sa.Column('return_pct', sa.Float(), nullable=True),
    sa.Column('mae_pct', sa.Float(), nullable=True),
    sa.Column('mfe_pct', sa.Float(), nullable=True),
    sa.Column('holding_days', sa.Integer(), nullable=True),
    sa.Column('benchmark_return', sa.Float(), nullable=True),
    sa.Column('closed_on', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recommendation_id')
    )
    with op.batch_alter_table('paper_positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_positions_ticker'), ['ticker'], unique=False)

    op.create_table('recommendation_outcomes',
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('horizon', sa.Integer(), nullable=False),
    sa.Column('forward_return', sa.Float(), nullable=False),
    sa.Column('benchmark_return', sa.Float(), nullable=True),
    sa.Column('excess_return', sa.Float(), nullable=True),
    sa.Column('matured_on', sa.Date(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('recommendation_id', 'horizon')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation_outcomes')
    with op.batch_alter_table('paper_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_positions_ticker'))

    op.drop_table('paper_positions')
    with op.batch_alter_table('factor_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_factor_snapshots_ticker'))
        batch_op.drop_index(batch_op.f('ix_factor_snapshots_rec_day'))

    op.drop_table('factor_snapshots')
    with op.batch_alter_table('committee_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_committee_reports_recommendation_id'))

    op.drop_table('committee_reports')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_ticker'))
        batch_op.drop_index(batch_op.f('ix_recommendations_scan_run_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_as_of'))
        batch_op.drop_index('ix_rec_ticker_asof')

    op.drop_table('recommendations')
    op.drop_table('watchlist')
    op.drop_table('securities')
    with op.batch_alter_table('scan_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_runs_as_of'))

    op.drop_table('scan_runs')
    with op.batch_alter_table('provider_health', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_health_name'))

    op.drop_table('provider_health')
    op.drop_table('price_bars')
    op.drop_table('portfolio_holdings')
    op.drop_table('model_versions')
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_calls_created_at'))

    op.drop_table('llm_calls')
    op.drop_table('llm_cache')
    op.drop_table('issues')
    op.drop_table('fundamentals_quarterly')
    op.drop_table('calibration_runs')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
